---
 - hosts: localhost # this is target section
   tasks:
    - name: running whoami command
      command: whoami
    - name: install httpd software
      yum:
       name: httpd
       state: present
    - name: printing message
      debug:
       msg: "hello world this is ansible"

